/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // 타슈 디자인 시스템 — 잠금 팔레트: brand 3단 + gray 8단 + danger. 그 외 색상 없음.
        primary: '#006A3C',
        'primary-dim': '#00542F',
        'primary-container': '#E8F5EE',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#006A3C',
        'inverse-primary': '#E8F5EE',
        surface: '#F7F8FA',
        'surface-bright': '#F7F8FA',
        'surface-dim': '#E2E5E9',
        'surface-variant': '#E2E5E9',
        'surface-tint': '#006A3C',
        'surface-container': '#EFF1F4',
        'surface-container-low': '#EFF1F4',
        'surface-container-high': '#E2E5E9',
        'surface-container-highest': '#E2E5E9',
        'surface-container-lowest': '#FFFFFF',
        'on-surface': '#14171C',
        'on-surface-variant': '#333A44',
        'inverse-surface': '#14171C',
        'inverse-on-surface': '#9CA3AD',
        background: '#F7F8FA',
        'on-background': '#14171C',
        outline: '#7A828C',
        'outline-variant': '#E2E5E9',
        error: '#E5484D',
        'error-dim': '#E5484D',
        'error-container': '#E5484D',
        'on-error': '#FFFFFF',
        'on-error-container': '#E5484D',
        gray: {
          50: '#F7F8FA',
          100: '#EFF1F4',
          200: '#E2E5E9',
          300: '#C7CCD3',
          400: '#9CA3AD',
          500: '#7A828C',
          700: '#333A44',
          900: '#14171C',
        },
      },
      fontFamily: {
        headline: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        body: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        label: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        sans: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '12px',
        sm: '8px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        // 규칙: 그림자는 바텀시트에만 1회 허용. 다른 곳은 전부 none.
        sheet: '0 -4px 24px rgba(20, 23, 28, 0.10)',
        breathe: 'none',
        'breathe-lg': 'none',
        float: 'none',
        'nav-top': 'none',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.32, 0.72, 0, 1)',
        'sheet-up': 'sheetUp 0.35s cubic-bezier(0.32, 0.72, 0, 1)',
        pulse: 'pulse 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        sheetUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        pulse: {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(0, 106, 60, 0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 15px rgba(0, 106, 60, 0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(0, 106, 60, 0)' },
        },
      },
    },
  },
  plugins: [],
}
