/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // 타슈 디자인 시스템 (그린 팔레트)
        primary: '#006a3c',
        'primary-dim': '#005c34',
        'primary-container': '#77f8ab',
        'primary-fixed': '#77f8ab',
        'primary-fixed-dim': '#68ea9e',
        'on-primary': '#cbffd8',
        'on-primary-container': '#005d34',
        'on-primary-fixed': '#004827',
        'on-primary-fixed-variant': '#00683b',
        'inverse-primary': '#77f8ab',
        secondary: '#595c5d',
        'secondary-dim': '#4d5051',
        'secondary-container': '#e1e3e4',
        'secondary-fixed': '#e1e3e4',
        'secondary-fixed-dim': '#d3d4d5',
        'on-secondary': '#f2f3f4',
        'on-secondary-container': '#505253',
        'on-secondary-fixed': '#3d4041',
        'on-secondary-fixed-variant': '#595c5d',
        tertiary: '#006479',
        'tertiary-dim': '#005769',
        'tertiary-container': '#00d5fe',
        'tertiary-fixed': '#00d5fe',
        'tertiary-fixed-dim': '#00c7ec',
        'on-tertiary': '#e0f6ff',
        'on-tertiary-container': '#004553',
        'on-tertiary-fixed': '#002f39',
        'on-tertiary-fixed-variant': '#004e5f',
        surface: '#f5f7fa',
        'surface-bright': '#f5f7fa',
        'surface-dim': '#d0d5d9',
        'surface-variant': '#d9dde1',
        'surface-tint': '#006a3c',
        'surface-container': '#e5e8ec',
        'surface-container-low': '#eef1f4',
        'surface-container-high': '#dfe3e7',
        'surface-container-highest': '#d9dde1',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#2c2f32',
        'on-surface-variant': '#595c5e',
        'inverse-surface': '#0b0f11',
        'inverse-on-surface': '#9a9da0',
        background: '#f5f7fa',
        'on-background': '#2c2f32',
        outline: '#74777a',
        'outline-variant': '#abadb0',
        error: '#b31b25',
        'error-dim': '#9f0519',
        'error-container': '#fb5151',
        'on-error': '#ffefee',
        'on-error-container': '#570008',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        breathe: '0 12px 24px -4px rgba(0, 106, 60, 0.08)',
        'breathe-lg': '0 16px 32px -4px rgba(0, 106, 60, 0.12)',
        float: '0 8px 20px rgba(0,0,0,0.05)',
        'nav-top': '0 -8px 20px rgba(0,0,0,0.05)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.32, 0.72, 0, 1)',
        'sheet-up': 'sheetUp 0.35s cubic-bezier(0.32, 0.72, 0, 1)',
        pulse: 'pulse 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        sheetUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        pulse: {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(0, 106, 60, 0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 15px rgba(0, 106, 60, 0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(0, 106, 60, 0)' },
        },
      },
    },
  },
  plugins: [],
}
